// template/solid/src/App.tsx
import type { Component } from "solid-js";
import logo from "./logo.png";

const App: Component = () => {
  return (
    <div class="flex flex-col items-center justify-center h-screen gap-32">
      <img src={logo} class="w-96 h-96 animate-bounce" alt="logo" />
      <p class="font-bold tracking-wider uppercase text-slate-600 text-64">
        👋 Bagstack <span class="text-blue-800">Solid</span>
      </p>
    </div>
  );
};

export default App;

// template/svelte/src/App.svelte
<script lang="ts">
  import logo from "./assets/svelte.png";
</script>

<main class="flex flex-col items-center justify-center h-screen gap-32">
  <img
    width="100"
    height="100"
    src={logo}
    alt="Svelte Logo"
    class="w-96 h-96 animate-bounce"
  />
  <h1 class="font-bold tracking-wider uppercase text-slate-600 text-64">
    👋 Bagstack <span class="text-orange">Svelte</span>
  </h1>
</main>
